### PR TITLE
troublet: add singlet/doublet posteriors to clusters.tsv

### PR DESCRIPTION
**Pull request by johnyaku**
The log probabilities in the  `clusters.tsv` file output by `troublet` are difficult to interpret.
In particular, it is not obvious how they relate to the singlet/doublet assignments.

I've adapted `troublet` to include additional columns for `singlet_posterior` and `doublet_posterior`, which I understand are the actual values used to determine assignments. We hope to use these to better interpret `troublet`  results.

No changes have been made to the methods used to calculate `singlet_posterior` and `doublet_posterior`.

### CODE REVIEW

**Comment by wheaton5** [comment]
if this is tested, I'll merge it. I'm not sure exactly what insight you will get besides how close a call it was. I agree posteriors are more interpretable than log likelihoods. But log likelihoods have a lot more dynamic range and tell you something about how much data went into the decision (the larger magnitude values come from more data). What you probably want is which variants had the most impact on making it a doublet which is possible to pull out, but not a very simple thing to do.

**Comment by johnyaku** [comment]
Hi Haynes, thanks for the quick response.

Yes, it has been tested, and we've been looking that posterior distributions for pools with ambient RNA estimates ranging from about 2% to about 23%. When ambient RNA is low, we get a very clean distribution with the overwhelming majority of barcodes designated as either high-confidence singlets or high-confidence doublets. But when ambient RNA is high, the picture is less clear cut, with a fair few barcodes designated as "singlets" having a moderately high `doublet_posterior`. 

My colleague interprets this as the barcode still representing a single cell, but with a degree of contamination by ambient RNA, so he wants to use the `doublet_posterior` value as a proxy for contamination to remove not just clear-cut doublets and "unassigned" barcodes but also any cell where the `doublet_posterior` is over a certain level. We could re-run `troublet` with different threshold settings to get new assignments, but `troublet` appears to be one of the more time-consuming steps in the pipeline, so we want to redo just the assignment based on our own custom filters. 

My conclusion from looking fairly closely at the `troublet` output is that `troublet` is very conservative, but my colleague wants to be ultra-conservative. We estimate that we should still have enough cells left over, even with these ultra-conservative filters.

Your suggestion about identifying which variants impact doublet calling is an interesting one, and I agree that it will be non-trivial, but might potentially allow us to keep "contaminated" cells while excising just those transcripts that appear to come from another sample.

 I'll give it some thought and you might get another PR in the future!

**Comment by wheaton5** [comment]
I would caution trusting the ambient RNA estimates too much. If you have a sample that was from a solid tissue that required harsh surfactants and other chemicals to get a good cell suspension, or the tissue itself is damaged such as a necrotic tumor, then yes, the ambient RNA can go to 20-35%. But full disclosure, the ambient RNA estimation is highly dependent on the initial clustering being high quality. Ive seen datasets with low UMI per cell which makes clustering harder. And the rare errors in clustering makes the ambient RNA estimation blow up. You could even simulate this by downsampling reads or umi. Your conclusions might be perfectly correct. I just wanted to let u know this insight.

**Comment by johnyaku** [comment]
We are not reading too much into the actual numbers of the ambient RNA estimates, but directionally they do appear to indicate issues with those particular pools. We ran four replicates of each pool (drawing four times from the same vial of dissociated cells), and the replicates with the sky-high ambient RNA were the first to be drawn. We're not sure exactly why, but it is conceivable that cell fragments floated nearer to the top and were extracted first. One of these "first out" replicates clogged and could not be captured, and all "first out" replicates had _much_ higher barcode counts than the others. (These are cancer samples, btw.)

All of this is consisent with poorer quality pools. We'll keep an eye on this in future, but ambient RNA estimates may turn out to be a good indicator of quality, even if we can't put too much weight on the actual number. 

Moreover, pools with low ambient RNA seem to separate out cleanly into singlets and doublets, with relatively few unassigned, and most posteriors very, very close to 1 or 0. But for pools with higher ambient RNA the signal is much more blurred, and we'd like to apply our own filters based on the singlet and doublet posteriors. 

I've just reviewed the `diff`: https://github.com/wheaton5/souporcell/pull/162/files

I also restored a couple of lines back to how they were. So only four lines changed, adding extra columns for `singlet_posterior` and `doublet_posterior`.

Finally, I also created a docker container. `Dockerfile` included in this branch but probably no need to include it in the PR. You can download it from here if you want to run tests: https://hub.docker.com/r/johnyaku/souporcell

I'm using this for our own tests, which should complete overnight (our time). I'll let you how it goes :)

**Comment by johnyaku** [comment]
Tests completed successfully. The output (`clusters.tsv`) is identical except for the addition of `singlet_posterior` and `doublet_posterior` columns. 

Look back at the results in detail, the `singlet_posterior` and `doublet_posterior` values explain the assignments clearly. But there are quite a few cases where the `log_prob_singleton` and `log_prob_doublet` values are both extremely small (and similar magnitude) and so the connection to the assignment is not obvious. Of course, the posterior values also take into account the scores for each pair of clusters, hence the very different posterior values even when the log probabilities are similar. So I think including the posterior values in the output adds a lot of clarity.

**Comment by wheaton5** [comment]
Merged. Do u think there should be more stringent assignment?

**Comment by johnyaku** [comment]
When ambient RNA is low and there is a very clear separation between "obvious singlets" and "obvious doublets" then I think the current assignment logic is pretty conservative. It is only when ambient RNA is high that the story gets a bit murkier. Interestingly, we are still able to recover a reasonable number of cells even with more stringent filtering. 

My colleague is looking into the downstream consequences of more stringent assignment/filtering. We'll let you know if it appears to be worthwhile :)

**Pull request merged**
